In [28]:
import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
        SELECT *
        FROM FACILITIES
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)
        
def rev_under_1000(conn):
    """
    Produces a list of facilities with a total revenue less than 1000
    Outputs facility name and total revenue, sorted by revenue
    Takes into account different cost structure between guests and members
    Question 10 from the Springboard project
    """
    cur = conn.cursor()
    
    query2 = """
        SELECT sub2.name, sub2.total_rev
        FROM(
    
            SELECT sub.name, SUM(sub.revPerBooking) as total_rev
                FROM (
                    SELECT f.name, b.facid,
                        CASE WHEN b.memid = 0 THEN b.slots * f.guestcost
                        ELSE b.slots * f.membercost END AS revPerBooking
                    FROM Bookings as b
            LEFT JOIN Facilities AS f
            ON b.facid = f.facid
        ) sub

    GROUP BY sub.name
    ORDER BY total_rev DESC) sub2
    WHERE sub2.total_rev < 1000.00;
    """
    cur.execute(query2)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)

def member_recos(conn):
    """
    Produces a report of members and who recommended them in alphabetic surname, firstname order. 
    Question 11 from the Springboard project
    """
    cur = conn.cursor()
    
    query3 = """
        SELECT m1.firstname, m1.surname, m2.firstname AS refname1,
            m2.surname AS refname2
        FROM Members as m1
        LEFT JOIN Members as m2 
            ON m1.recommendedby = m2.memid
        ORDER BY m1.surname, m1.firstname;
    """
    cur.execute(query3)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)    

def facility_usage_by_members(conn):
    """
    Produces a report of the facilities with usage by member, not including usage by guests
    Question 12 from the Springboard project
    """
    cur = conn.cursor()
    
    query4 = """
        SELECT f.name, SUM(b.slots) AS Total_Slots
        FROM Bookings as b
        LEFT JOIN Facilities as f
            ON b.facid = f.facid
        WHERE b.memid != 0
        GROUP BY b.facid;
    """
    cur.execute(query4)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)    

def facility_usage_month(conn):
    """
    Produces a report of the facilities usage by month, not including guest usage
    Question 13 from the Springboard project
    """
    cur = conn.cursor()
    
    query5 = """
        SELECT strftime('%m', b.starttime) AS Month, f.name, SUM(b.slots) AS totalSlots
        FROM Bookings AS b
        LEFT JOIN Facilities as f
        ON b.facid = f.facid
        WHERE b.memid != 0
        GROUP BY b.facid, Month;
    """
    cur.execute(query5)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)    
        
        
def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        #print("2. Query all tasks")
        facility_usage_month(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
('07', 'Tennis Court 1', 201)
('08', 'Tennis Court 1', 339)
('09', 'Tennis Court 1', 417)
('07', 'Tennis Court 2', 123)
('08', 'Tennis Court 2', 345)
('09', 'Tennis Court 2', 414)
('07', 'Badminton Court', 165)
('08', 'Badminton Court', 414)
('09', 'Badminton Court', 507)
('07', 'Table Tennis', 98)
('08', 'Table Tennis', 296)
('09', 'Table Tennis', 400)
('07', 'Massage Room 1', 166)
('08', 'Massage Room 1', 316)
('09', 'Massage Room 1', 402)
('07', 'Massage Room 2', 8)
('08', 'Massage Room 2', 18)
('09', 'Massage Room 2', 28)
('07', 'Squash Court', 50)
('08', 'Squash Court', 184)
('09', 'Squash Court', 184)
('07', 'Snooker Table', 140)
('08', 'Snooker Table', 316)
('09', 'Snooker Table', 404)
('07', 'Pool Table', 110)
('08', 'Pool Table', 303)
('09', 'Pool Table', 443)